version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "RemoteTeamBuilding"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1737k2d2y5bfc"
s3_prefix = "RemoteTeamBuilding"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
